Feature/optimizing repository layer
typearea/dembelo pull request #214
Opened 2016-09-10 19:49 UTC by hebestreit

Hier ein Beispiel, wie man die Logik aus den Controllern bekommt und die Model-Schicht strukturieren könnte.

2016-09-13 15:50 UTC, michaelgiesler commented
- [ ] Bitte den Lizenzhinweis in jeder Datei nicht vergessen
- [ ] Dateien verschieben, nicht kopieren - um Leichen zu verhindern

Darüber hinaus sind beispielsweise die ODM/*Repository.php ziemlich redundant. Das save() könnte in ein ODM/AbstractRepository.php verschoben werden.

2016-09-14 21:07 UTC, hebestreit commented
Die Idee mit AbstractRepository finde ich super!
Was meinst du genau mit "Dateien verschieben, nicht kopieren - um Leichen zu verhindern" ?

Lizenzhinweis erweiter ich gerne.

2016-09-14 21:23 UTC, michaelgiesler commented
Du hast beispielsweise die index.html.twig nach dashboard.html.twig kopiert. Bitte entferne die index.html.twig. Ich weiß gerade nicht, ob es auch andere Dateien betrifft - aber hier ist es mir aufgefallen.

2016-09-15 07:12 UTC, michaelgiesler commented
Du kannst dich bei Bedarf noch in die /AUTHORS-Datei eintragen - für deine 15min Ruhm.

2016-09-17 11:34 UTC, hebestreit commented
Habe deine Anderungswünsche umgesetzt. Jedoch können wir das mit dem AbstractRepository nicht umsetzen, da wir als Typehint unser Document angeben und dieser pro Repository unterschiedlich ist.

2016-09-19 20:07 UTC, michaelgiesler requested changes
Im Lizenzhinweis muss natürlich in deinem Falle bei neuen Dateien "2016 Daniel Hebestreit" stehen.
Das kannst du übrigens in PHPStorm einrichten:
Settings => Editor => File and Code Templates => Includes => PHP File Header

2016-09-19 20:07 UTC, michaelgiesler commented on www/src/DembeloMain/Controller/Dashboard/DefaultController.php
> +    private $templating;
phpDoc fehlt für $templating

2016-09-20 18:24 UTC, michaelgiesler commented
Clean Code sagt: "Don't repeat yourself". Darum lass uns die redundante Save-Methode mit den redundanten Unittests vermeiden. Mein Vorschlag:

```
class AbstractRepository {
    public function save(DocumentInterface $document)
    {
        if (!$document instanceof $this->getClassName()) {
            throw new Exception('is nich');
        }
        $this->dm->persist($document);
        $this->dm->flush();

        return $document;
    }
}
```

2016-09-20 19:55 UTC, hebestreit commented
Da bin ich einerseits voll bei dir, jedoch wäre der TypeHint und das Interface DocumentInterface überflüssig. Ich persönlich würde es so belassen, da der Mehrwert eines konkreten TypeHint für mich höher ist. Somit hätte das z.B. UserRepositoryInterface als TypeHint save (DocumentInterface $user). Wodurch eine Abhängigkeit zu einer Klasse besteht, die lediglich den faulen Entwickler die Arbeit erleichtert. :)

Sollte es im Laufe der Entwicklung notwendig sein, eine Sonderbehandlung des  User Document zu implementieren, dann wäre hier

2016-09-20 19:56 UTC, hebestreit commented
... ein TypeHint des richtigen Document ein Vorteil.

2016-09-21 07:02 UTC, michaelgiesler commented
Ja, Typehint wäre schön. So wie es jetzt ist, finde ich es aber unschön: die save-Methode findet sich in - abgesehen vom Typehint - identisch für jede Document-Klasse. Dadurch gibt es den dazugehörigen Test mehrfach für jede Documentklasse. Wenn ich nun beispielsweise den Test darum erweitern will, dass geprüft wird, ob die $dm-Funktionen aufgerufen werden, muss ich dies mehrfach tun. Und bei weiteren zukünftigen Document-Klassen den Test sogar rüberkopieren. Wenn ich in der save()-Methode beispielsweise ein Logging einbauen will, muss ich das per Copy&Paste mehrfach tun und daraufhin per Copy&Paste alle Unittests erweitern. Das widerspricht dem DRY-Prinzip (das nicht nur im Clean Code gilt). 

**Aber es gibt ja Traits!**
Siehe: http://stackoverflow.com/questions/6856231/traits-parent-self-type-hints-in-php-5-4
save() wird in den Trait verschoben, und wird mit dem Typehint "self" nur Objekte der jeweiligen Klasse akzeptieren. Ich habe "self" in der PHP-Doku weder im Abschnitt Trait noch im Abschnitt Typehint gefunden. Ein kleiner Test in PHP 5.5 hat aber gezeigt, dass wir hier genau das gewünscht Verhalten bekämen.
Vorteile:
1) ich sehe erstmalig Traits in freier Wildbahn - hast du schonmal welche benutzt?
2) Typehint bleibt erhalten
3) Code-Duplikation wird vermieden
4) save() muss nicht im Unittest der Dokument-Klassen getestet werden. Über PHPUnit kann man sicherlich auch Traits direkt testen

Können wir uns darauf einigen?

2016-09-22 20:10 UTC, michaelgiesler approved these changes

2016-09-22 20:12 UTC, merged