twine reimport resolves #226
typearea/dembelo pull request #241
Opened 2016-10-15 16:10 UTC by michaelgiesler

2016-10-23 19:29 UTC, hebestreit requested changes

2016-10-23 19:29 UTC, hebestreit commented on www/src/AdminBundle/Command/ImportCommand.php
>      private $author = "";
Bitte Single-Quotes verwenden

2016-10-23 19:29 UTC, hebestreit commented on www/src/AdminBundle/Command/ImportCommand.php
> +         * @var $repositoryLicensee EntityRepository
Hier kannst du direkt das LicenseeRepositoryInterface angeben anstatt EntityRepository.
Ebenfalls solltest du die Methode "findOneByName" im Interface erweitern.

2016-10-23 19:29 UTC, hebestreit commented on www/src/AdminBundle/Controller/DefaultController.php
> +            $obj = new StdClass();
Hier würde ich dir empfehlen ein Array anstatt einer StdClass zu nutzen, da dadurch Speicher gespart wird und meiner Meinung kein Vorteil entsteht.

http://stackoverflow.com/questions/18640607/what-is-better-stdclass-or-object-array-to-store-related-data

2016-10-23 19:29 UTC, hebestreit commented on www/src/AdminBundle/Model/ImportTwine.php
> +            throw new Exception('no licensee available');
Ich finde es immer sinnvoll eine separate Exception Klasse zu definieren. Jede Exception die geworfen wird, bekommt eine eigene Klasse.

```
        throw new UndefinedLicenseeException(
            UndefinedLicenseeException::UNDEFINED_MESSAGE,
            UndefinedLicenseeException::UNDEFINED_CODE
        );
```

Alternativ könntest du auch auf die Message und Code verzichten und nur die Exception werfen, da diese aussagekräftig genug ist.

```
class UndefinedLicenseeException extends \Exception
{
    const UNDEFINED_MESSAGE = 'No licensee available';
    const UNDEFINED_CODE = 400;
}
```

2016-10-23 19:29 UTC, hebestreit commented on www/src/AdminBundle/Model/ImportTwine.php
> +namespace AdminBundle\Model;
Den Namespace "Model" finde ich nicht passend. Würdest du dich mit "Import" stattdessen zufrieden geben, da der Import für mich mehr Business-Logik beeinhaltet als dass es in die Model-Schicht gehört.

2016-10-23 19:29 UTC, hebestreit commented on www/src/AdminBundle/Model/ImportTwine.php
> +    private function startElementStoryData($name, $attrs)
hier bitte einen Typehint hinzufügen:

`private function startElementStoryData($name, array $attrs)`

2016-10-23 19:29 UTC, hebestreit commented on www/src/DembeloMain/Document/Importfile.php
> +    protected $orgname;
Was ist mit orgname gemeint? Ich würde lieber ein paar mehr Bytes investieren aber dann wissen, was hier gemeint ist :-) Außerdem meckert PhpStorm das auch als "kenn das Wort nicht" an.

2016-10-23 19:29 UTC, hebestreit commented on www/src/DembeloMain/Model/Repository/Doctrine/ODM/TextNodeRepository.php
> +        $textnodes = $this->findBy(
Hier würde ich die Methode findOneBy() nutzen.

```
public function findByTwineId(Importfile $importfile, $twineId)
{
    $textnode = $this->findOneBy(
        array(
            'importfileId' => new MongoId($importfile->getId()),
            'twineId' => $twineId,
        )
    );

    return $textnode;
}
```

2016-10-23 19:29 UTC, hebestreit commented on www/src/DembeloMain/Tests/Model/Repository/Doctrine/ODM/TextNodeRepositoryTest.php
> +     * @var \Doctrine\ORM\EntityManager
Das solltest du in Doctrine\ODM\MongoDB\DocumentManager ändern, da wir nicht das ORM von Doctrine nutzen. Dann werden im Code auch ein paar "Warnings" weniger angezeigt. Demnach müsste die Variable in $dm geändert werden.

2016-10-23 19:29 UTC, hebestreit commented on www/src/DembeloMain/Tests/Model/Repository/Doctrine/ODM/TopicRepositoryTest.php
> +     * @var \Doctrine\ORM\EntityManager
Das solltest du in Doctrine\ODM\MongoDB\DocumentManager ändern, da wir nicht das ORM von Doctrine nutzen. Dann werden im Code auch ein paar "Warnings" weniger angezeigt. Demnach müsste die Variable in $dm geändert werden.

2016-10-23 19:29 UTC, hebestreit commented on www/src/DembeloMain/Model/Repository/Doctrine/ODM/TextNodeRepository.php
> +     * @return array
```
 * @return Textnode[]
```

2016-10-23 19:29 UTC, hebestreit commented on www/src/DembeloMain/Tests/Model/Repository/Doctrine/ODM/TextNodeRepositoryTest.php
> +        $this->assertEquals(1, count($textnodes));
PhpUnit liefert dafür direkt eine passende Methode

```
    $this->assertCount(1, $textnodes);
```

2016-10-23 19:29 UTC, hebestreit commented on www/src/DembeloMain/Tests/Model/Repository/Doctrine/ODM/TextNodeRepositoryTest.php
> +        $this->assertEquals([], $textnodes);
```
    $this->assertEmpty($textnodes);
```

2016-10-23 19:29 UTC, hebestreit commented on www/src/DembeloMain/Tests/Model/Repository/Doctrine/ODM/TextNodeRepositoryTest.php
> +        $this->assertEquals(1, count($textnodes));
```
    $this->assertCount(1, $textnodes);
```

2016-10-23 19:29 UTC, hebestreit commented on www/src/DembeloMain/Tests/Model/Repository/Doctrine/ODM/TextNodeRepositoryTest.php
> +        $retVal = $this->repository->findByTwineId($importfile, 'twineId');
$retVal bitte sinnvoller bennen z.B $textnode

2016-10-23 19:29 UTC, hebestreit commented on www/src/DembeloMain/Tests/Model/Repository/Doctrine/ODM/TextNodeRepositoryTest.php
> +        $cursor = $this->repository->createQueryBuilder()->find()->refresh()->getQuery()->execute();
Kannst du hier nicht $this->repository->findAll() nutzen?

2016-10-23 19:29 UTC, hebestreit commented on www/src/DembeloMain/Tests/Model/Repository/Doctrine/ODM/TextNodeRepositoryTest.php
> +        foreach ($cursor as $c) {
$c bitte sinnvoll benamen

2016-10-23 20:45 UTC, michaelgiesler commented on www/src/AdminBundle/Model/ImportTwine.php
> +namespace AdminBundle\Model;
Wie würdest du "Model" definieren? Als Datenbankmodel? Gibt es hier Konventionen von Symfony? Ich würde ungerne Klassen direkt im Bundle-Verzeichnis ablegen (Adminbundle/Import.php). Insofern war ich bisher davon ausgegangen, den "eigentlich Code" im Model-Verzeichnis abzulegen.

2016-10-23 20:47 UTC, michaelgiesler commented on www/src/AdminBundle/Model/ImportTwine.php
> +            throw new Exception('no licensee available');
Ja, du hast Recht. Dieses Refactoring übersteigt aber das, was ich in diesem Issue erreichen will.
Refactoring != komplett neu machen

2016-10-23 21:06 UTC, michaelgiesler commented on www/src/DembeloMain/Tests/Model/Repository/Doctrine/ODM/TextNodeRepositoryTest.php
> +        $cursor = $this->repository->createQueryBuilder()->find()->refresh()->getQuery()->execute();
Hier musste ich relative lange herumprobieren, um Doctrine dazu zu bewegen, eine neue Datenbankabfrage zu machen, statt die bereits vorhanden Objekte aus dem Cache zurückzugeben. Stack Overflow tendierte hier stark zum Querybuilder, um refresh() nutzen zu können.

2016-10-24 22:34 UTC, hebestreit commented on www/src/AdminBundle/Model/ImportTwine.php
> +namespace AdminBundle\Model;
Die Klasse würde ich unter dem Namespace "UseCase", "Import" oder "Command" ablegen. Für meinen persönlichen Geschmack befindet sich in dieser Klasse zu viel Logik, die nichts mit der Model-Schicht zu tun hat. 

Was hälst du denn von AdminBundle\Import\Twine ?

2016-10-24 22:35 UTC, hebestreit commented on www/src/AdminBundle/Model/ImportTwine.php
> +            throw new Exception('no licensee available');
Ja da kann ich dich vollkommen verstehen. Dann hoffe ich mal, dass ich in einem neuen PR beglückt werde :-)

2016-10-24 22:36 UTC, hebestreit commented on www/src/DembeloMain/Tests/Model/Repository/Doctrine/ODM/TextNodeRepositoryTest.php
> +        $cursor = $this->repository->createQueryBuilder()->find()->refresh()->getQuery()->execute();
Hachja... das sind die Dinge, die einen verzweifeln lassen.

2016-10-27 21:12 UTC, michaelgiesler commented on www/src/AdminBundle/Model/ImportTwine.php
> +namespace AdminBundle\Model;
Ich bevorzuge weiterhin AdminBundle\Model\ImportTwine.

AdminBundle/Import/... finde ich ungünstig, weil es das Wurzelverzeichnis "zumüllt". Dort liegen derzeit: Command/, Controller/, Document/, Resources/, Tests/  - alles Verzeichnisse, die Symfony-spezifisch sind. Weitere Dembelo-spezifische Klassen/Verzeichnisse sollen da nicht kreuz und quer zwischenliegen.

AdminBundle/Command trifft nicht zu, da die Import-Klasse sowohl vom Command als auch vom Controller aus angesprochen wird.

AdminBundle/UseCase trifft nicht zu, weil es sich nicht um einen UseCase handelt, der in der Klasse implementiert ist.

Ich habe noch die Empfehlungen Service und Utils gefunden - beides nicht so glücklich, wie ich finde.

Der Begriff Model bezieht sich in Symfony nicht ausschließlich auf Datenbankmodels, sondern im Sinne von MVC auf Logik im Allgemeinen, zumal in DembeloMain/Model/Repository/Doctrine in einer tieferen Schicht unterhalb von Model wieder die Assoziation zur Datenbank aufgenommen wird. Für mein Verständnis ist die Model-Schicht genau dafür da: die Logik. Wenn du hier eine andere Auffassung hast, klär mich auf.

2016-11-07 16:31 UTC, merged